<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-9K58VOG" name="TestCase.ServiceTest.InformationService" tests="1" failures="1" timestamp="03 六月 2018 05:50:00 GMT" time="1.826" errors="0">
  <testcase name="informationServiceTest" time="1.826" classname="TestCase.ServiceTest.InformationService">
    <failure type="java.lang.AssertionError" message="网页url与预期不符合 expected [http://lib.zjxu.edu.cn/PCWeb/JointReferenceConsult/intelligenceServiceDetailTab/id/18] but found [http://lib.zjxu.edu.cn/PCWeb/JointReferenceConsult/intelligenceServiceDetailTab/id/16]">
      <![CDATA[java.lang.AssertionError: 网页url与预期不符合 expected [http://lib.zjxu.edu.cn/PCWeb/JointReferenceConsult/intelligenceServiceDetailTab/id/18] but found [http://lib.zjxu.edu.cn/PCWeb/JointReferenceConsult/intelligenceServiceDetailTab/id/16]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Utils.ActionBot.urlAssert(ActionBot.java:303)
at TestCase.ServiceTest.InformationService.informationServiceTest(InformationService.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- informationServiceTest -->
</testsuite> <!-- TestCase.ServiceTest.InformationService -->
